image: git.m4xw.net:4567/libretro/dependencies/anglestrap:latest

stages:
  - build

.build_def: &build_definition
  stage: build
  artifacts:
    paths:
      - angle/out/*/lib*.so
      - angle/out/*/args.gn
      - angle/include
  before_script:
    - ./prep-gitlab.sh
    

.build_def_normal: &build_definition_normal
  <<: *build_definition
  script: |
    echo "Buildstrapping for ${TARGET}";
    ./buildstrap.sh ${TARGET} linux;

.build_def_ggp: &build_definition_ggp
  <<: *build_definition
  script: |
    echo "Buildstrapping for ${TARGET} ggp";
    ./buildstrap.sh ${TARGET} ggp;

Debug:
  variables:
    TARGET: Debug
  <<: *build_definition_normal

Release:
  variables:
    TARGET: Release
  <<: *build_definition_normal

Debug-ggp:
  variables:
    TARGET: Debug
  <<: *build_definition_ggp

Release-ggp:
  variables:
    TARGET: Release
  <<: *build_definition_ggp
